from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorSeverity(StrEnum):
    ERROR = "error"
    CRITICAL = "critical"


class ErrorCode(StrEnum):
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"
    CONFIG_INVALID = "CONFIG_INVALID"
    RUNTIME_UNSUPPORTED = "RUNTIME_UNSUPPORTED"
    PATH_NOT_WRITABLE = "PATH_NOT_WRITABLE"
    SERIALIZATION_FAILED = "SERIALIZATION_FAILED"
    INVALID_INPUT = "INVALID_INPUT"
    PLUGIN_MANIFEST_INVALID = "PLUGIN_MANIFEST_INVALID"
    PLUGIN_CONTRACT_UNSUPPORTED = "PLUGIN_CONTRACT_UNSUPPORTED"
    PLUGIN_CAPABILITY_DENIED = "PLUGIN_CAPABILITY_DENIED"
    PLUGIN_INPUT_INVALID = "PLUGIN_INPUT_INVALID"
    PLUGIN_AUTHORIZATION_INVALID = "PLUGIN_AUTHORIZATION_INVALID"
    PLUGIN_NOT_READY = "PLUGIN_NOT_READY"
    PLUGIN_EXECUTION_FAILED = "PLUGIN_EXECUTION_FAILED"
    PLUGIN_RESULT_INVALID = "PLUGIN_RESULT_INVALID"
    PLUGIN_LIMIT_EXCEEDED = "PLUGIN_LIMIT_EXCEEDED"
    PLUGIN_DUPLICATE_ID = "PLUGIN_DUPLICATE_ID"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    OPERATION_CANCELLED = "OPERATION_CANCELLED"
    DATABASE_PATH_INVALID = "DATABASE_PATH_INVALID"
    DATABASE_PARENT_NOT_WRITABLE = "DATABASE_PARENT_NOT_WRITABLE"
    DATABASE_PERMISSION_POLICY_FAILED = "DATABASE_PERMISSION_POLICY_FAILED"
    DATABASE_SYMLINK_UNSAFE = "DATABASE_SYMLINK_UNSAFE"
    DATABASE_OPEN_FAILED = "DATABASE_OPEN_FAILED"
    DATABASE_BUSY = "DATABASE_BUSY"
    DATABASE_PRAGMA_FAILED = "DATABASE_PRAGMA_FAILED"
    DATABASE_PRAGMA_MISMATCH = "DATABASE_PRAGMA_MISMATCH"
    DATABASE_CONNECTION_CLOSED = "DATABASE_CONNECTION_CLOSED"
    DATABASE_INTEGRITY_FAILED = "DATABASE_INTEGRITY_FAILED"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    MIGRATION_CHECKSUM_MISMATCH = "MIGRATION_CHECKSUM_MISMATCH"
    MIGRATION_ORDER_INVALID = "MIGRATION_ORDER_INVALID"
    MIGRATION_HISTORY_INVALID = "MIGRATION_HISTORY_INVALID"
    MIGRATION_METADATA_INVALID = "MIGRATION_METADATA_INVALID"
    TRANSACTION_NOT_ACTIVE = "TRANSACTION_NOT_ACTIVE"
    TRANSACTION_ALREADY_COMMITTED = "TRANSACTION_ALREADY_COMMITTED"
    TRANSACTION_ALREADY_ROLLED_BACK = "TRANSACTION_ALREADY_ROLLED_BACK"
    TRANSACTION_COMMIT_FAILED = "TRANSACTION_COMMIT_FAILED"
    TRANSACTION_ROLLBACK_FAILED = "TRANSACTION_ROLLBACK_FAILED"
    DOMAIN_VALIDATION_FAILED = "DOMAIN_VALIDATION_FAILED"
    WORKSPACE_ALREADY_ARCHIVED = "WORKSPACE_ALREADY_ARCHIVED"
    WORKSPACE_INVALID_STATE = "WORKSPACE_INVALID_STATE"
    ENGAGEMENT_INVALID_TRANSITION = "ENGAGEMENT_INVALID_TRANSITION"
    ENGAGEMENT_AUTHORIZATION_REQUIRED = "ENGAGEMENT_AUTHORIZATION_REQUIRED"
    ENGAGEMENT_COMPLETION_REQUIRES_END_AT = "ENGAGEMENT_COMPLETION_REQUIRES_END_AT"
    ENGAGEMENT_ALREADY_ARCHIVED = "ENGAGEMENT_ALREADY_ARCHIVED"
    PERSISTENCE_MAPPING_FAILED = "PERSISTENCE_MAPPING_FAILED"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_NAME_CONFLICT = "WORKSPACE_NAME_CONFLICT"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    WORKSPACE_ARCHIVED = "WORKSPACE_ARCHIVED"
    ENGAGEMENT_NOT_FOUND = "ENGAGEMENT_NOT_FOUND"
    ENGAGEMENT_ARCHIVED = "ENGAGEMENT_ARCHIVED"
    ENGAGEMENT_NAME_CONFLICT = "ENGAGEMENT_NAME_CONFLICT"
    ENGAGEMENT_WORKSPACE_IMMUTABLE = "ENGAGEMENT_WORKSPACE_IMMUTABLE"
    TARGET_VALUE_INVALID = "TARGET_VALUE_INVALID"
    TARGET_CONTROL_CHARACTER = "TARGET_CONTROL_CHARACTER"
    TARGET_WILDCARD_INVALID = "TARGET_WILDCARD_INVALID"
    TARGET_IP_INVALID = "TARGET_IP_INVALID"
    TARGET_NETWORK_UNSAFE = "TARGET_NETWORK_UNSAFE"
    TARGET_URL_INVALID = "TARGET_URL_INVALID"
    TARGET_KIND_INVALID = "TARGET_KIND_INVALID"
    TARGET_ALREADY_ARCHIVED = "TARGET_ALREADY_ARCHIVED"
    TARGET_SCOPE_MISMATCH = "TARGET_SCOPE_MISMATCH"
    TARGET_NOT_FOUND = "TARGET_NOT_FOUND"
    INVALID_SCOPE_TRANSITION = "INVALID_SCOPE_TRANSITION"
    SCOPE_ARCHIVED = "SCOPE_ARCHIVED"
    SCOPE_AUTHORIZATION_REQUIRED = "SCOPE_AUTHORIZATION_REQUIRED"
    SCOPE_VALIDATION_REQUIRED = "SCOPE_VALIDATION_REQUIRED"
    SCOPE_NOT_DRAFT = "SCOPE_NOT_DRAFT"
    SCOPE_NOT_FOUND = "SCOPE_NOT_FOUND"
    SCOPE_NAME_CONFLICT = "SCOPE_NAME_CONFLICT"
    AUTHORIZED_SCOPE_IMMUTABLE = "AUTHORIZED_SCOPE_IMMUTABLE"
    TARGET_DUPLICATE = "TARGET_DUPLICATE"
    SCOPE_NOT_AUTHORIZED = "SCOPE_NOT_AUTHORIZED"
    SCOPE_EXPIRED = "SCOPE_EXPIRED"
    TARGET_EXCLUDED = "TARGET_EXCLUDED"
    TARGET_OUT_OF_SCOPE = "TARGET_OUT_OF_SCOPE"
    TASK_INVALID_TRANSITION = "TASK_INVALID_TRANSITION"
    TASK_AUTHORIZATION_REQUIRED = "TASK_AUTHORIZATION_REQUIRED"
    TASK_AUTHORIZATION_SCOPE_MISMATCH = "TASK_AUTHORIZATION_SCOPE_MISMATCH"
    TASK_AUTHORIZATION_TARGET_MISMATCH = "TASK_AUTHORIZATION_TARGET_MISMATCH"
    TASK_AUTHORIZATION_EXPIRED = "TASK_AUTHORIZATION_EXPIRED"
    TASK_EXECUTION_SPEC_MISMATCH = "TASK_EXECUTION_SPEC_MISMATCH"
    TASK_IDENTITY_IMMUTABLE = "TASK_IDENTITY_IMMUTABLE"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    EXECUTION_SPEC_INVALID = "EXECUTION_SPEC_INVALID"
    EXECUTION_START_FAILED = "EXECUTION_START_FAILED"
    RECON_ASSET_DUPLICATE = "RECON_ASSET_DUPLICATE"
    RECON_CORRELATION_CONFLICT = "RECON_CORRELATION_CONFLICT"
    RECON_PARENT_NOT_FOUND = "RECON_PARENT_NOT_FOUND"
    RECON_RESULT_INVALID = "RECON_RESULT_INVALID"
    RECON_AUTHORIZATION_INVALID = "RECON_AUTHORIZATION_INVALID"
    RECON_RECORD_INVALID = "RECON_RECORD_INVALID"
    RECON_NOT_FOUND = "RECON_NOT_FOUND"
    RECON_EVIDENCE_INVALID = "RECON_EVIDENCE_INVALID"
    RECON_EVIDENCE_NOT_FOUND = "RECON_EVIDENCE_NOT_FOUND"
    RECON_EVIDENCE_ARCHIVED = "RECON_EVIDENCE_ARCHIVED"
    RECON_EVIDENCE_PROVENANCE_INVALID = "RECON_EVIDENCE_PROVENANCE_INVALID"
    RECON_EVIDENCE_DUPLICATE = "RECON_EVIDENCE_DUPLICATE"
    EVIDENCE_QUERY_INVALID = "EVIDENCE_QUERY_INVALID"
    EVIDENCE_QUERY_UNBOUNDED = "EVIDENCE_QUERY_UNBOUNDED"
    EVIDENCE_QUERY_LIMIT_EXCEEDED = "EVIDENCE_QUERY_LIMIT_EXCEEDED"
    EVIDENCE_QUERY_CURSOR_INVALID = "EVIDENCE_QUERY_CURSOR_INVALID"
    EVIDENCE_QUERY_CONTEXT_INVALID = "EVIDENCE_QUERY_CONTEXT_INVALID"
    EVIDENCE_QUERY_STORAGE_FAILED = "EVIDENCE_QUERY_STORAGE_FAILED"
    REPORT_QUERY_INVALID = "REPORT_QUERY_INVALID"
    REPORT_BUDGET_EXCEEDED = "REPORT_BUDGET_EXCEEDED"
    REPORT_DATA_INCONSISTENT = "REPORT_DATA_INCONSISTENT"
    REPORT_PROJECTION_INVALID = "REPORT_PROJECTION_INVALID"
    OFFLINE_FIXTURE_INVALID = "OFFLINE_FIXTURE_INVALID"
    OFFLINE_FIXTURE_EXECUTION_FAILED = "OFFLINE_FIXTURE_EXECUTION_FAILED"
    OFFLINE_FIXTURE_CONTEXT_INVALID = "OFFLINE_FIXTURE_CONTEXT_INVALID"


EXIT_CODES: dict[ErrorCode, int] = {
    ErrorCode.CONFIG_NOT_FOUND: 2,
    ErrorCode.CONFIG_INVALID: 2,
    ErrorCode.RUNTIME_UNSUPPORTED: 3,
    ErrorCode.PATH_NOT_WRITABLE: 3,
    ErrorCode.SERIALIZATION_FAILED: 4,
    ErrorCode.INVALID_INPUT: 4,
    ErrorCode.PLUGIN_MANIFEST_INVALID: 5,
    ErrorCode.PLUGIN_CONTRACT_UNSUPPORTED: 5,
    ErrorCode.PLUGIN_CAPABILITY_DENIED: 5,
    ErrorCode.PLUGIN_INPUT_INVALID: 4,
    ErrorCode.PLUGIN_AUTHORIZATION_INVALID: 4,
    ErrorCode.PLUGIN_NOT_READY: 4,
    ErrorCode.PLUGIN_EXECUTION_FAILED: 5,
    ErrorCode.PLUGIN_RESULT_INVALID: 5,
    ErrorCode.PLUGIN_LIMIT_EXCEEDED: 5,
    ErrorCode.PLUGIN_DUPLICATE_ID: 5,
    ErrorCode.INTERNAL_ERROR: 10,
    ErrorCode.OPERATION_CANCELLED: 130,
    ErrorCode.DATABASE_PATH_INVALID: 3,
    ErrorCode.DATABASE_PARENT_NOT_WRITABLE: 3,
    ErrorCode.DATABASE_PERMISSION_POLICY_FAILED: 3,
    ErrorCode.DATABASE_SYMLINK_UNSAFE: 3,
    ErrorCode.DATABASE_OPEN_FAILED: 3,
    ErrorCode.DATABASE_BUSY: 3,
    ErrorCode.DATABASE_PRAGMA_FAILED: 3,
    ErrorCode.DATABASE_PRAGMA_MISMATCH: 3,
    ErrorCode.DATABASE_CONNECTION_CLOSED: 3,
    ErrorCode.DATABASE_INTEGRITY_FAILED: 3,
    ErrorCode.MIGRATION_FAILED: 3,
    ErrorCode.MIGRATION_CHECKSUM_MISMATCH: 3,
    ErrorCode.MIGRATION_ORDER_INVALID: 3,
    ErrorCode.MIGRATION_HISTORY_INVALID: 3,
    ErrorCode.MIGRATION_METADATA_INVALID: 3,
    ErrorCode.TRANSACTION_NOT_ACTIVE: 4,
    ErrorCode.TRANSACTION_ALREADY_COMMITTED: 4,
    ErrorCode.TRANSACTION_ALREADY_ROLLED_BACK: 4,
    ErrorCode.TRANSACTION_COMMIT_FAILED: 3,
    ErrorCode.TRANSACTION_ROLLBACK_FAILED: 3,
    ErrorCode.DOMAIN_VALIDATION_FAILED: 4,
    ErrorCode.WORKSPACE_ALREADY_ARCHIVED: 4,
    ErrorCode.WORKSPACE_INVALID_STATE: 4,
    ErrorCode.ENGAGEMENT_INVALID_TRANSITION: 4,
    ErrorCode.ENGAGEMENT_AUTHORIZATION_REQUIRED: 4,
    ErrorCode.ENGAGEMENT_COMPLETION_REQUIRES_END_AT: 4,
    ErrorCode.ENGAGEMENT_ALREADY_ARCHIVED: 4,
    ErrorCode.PERSISTENCE_MAPPING_FAILED: 3,
    ErrorCode.WORKSPACE_NOT_FOUND: 4,
    ErrorCode.WORKSPACE_NAME_CONFLICT: 4,
    ErrorCode.CONCURRENCY_CONFLICT: 4,
    ErrorCode.WORKSPACE_ARCHIVED: 4,
    ErrorCode.ENGAGEMENT_NOT_FOUND: 4,
    ErrorCode.ENGAGEMENT_ARCHIVED: 4,
    ErrorCode.ENGAGEMENT_NAME_CONFLICT: 4,
    ErrorCode.ENGAGEMENT_WORKSPACE_IMMUTABLE: 4,
    ErrorCode.TARGET_VALUE_INVALID: 4,
    ErrorCode.TARGET_CONTROL_CHARACTER: 4,
    ErrorCode.TARGET_WILDCARD_INVALID: 4,
    ErrorCode.TARGET_IP_INVALID: 4,
    ErrorCode.TARGET_NETWORK_UNSAFE: 4,
    ErrorCode.TARGET_URL_INVALID: 4,
    ErrorCode.TARGET_KIND_INVALID: 4,
    ErrorCode.TARGET_ALREADY_ARCHIVED: 4,
    ErrorCode.TARGET_SCOPE_MISMATCH: 4,
    ErrorCode.TARGET_NOT_FOUND: 4,
    ErrorCode.INVALID_SCOPE_TRANSITION: 4,
    ErrorCode.SCOPE_ARCHIVED: 4,
    ErrorCode.SCOPE_AUTHORIZATION_REQUIRED: 4,
    ErrorCode.SCOPE_VALIDATION_REQUIRED: 4,
    ErrorCode.SCOPE_NOT_DRAFT: 4,
    ErrorCode.SCOPE_NOT_FOUND: 4,
    ErrorCode.SCOPE_NAME_CONFLICT: 4,
    ErrorCode.AUTHORIZED_SCOPE_IMMUTABLE: 4,
    ErrorCode.TARGET_DUPLICATE: 4,
    ErrorCode.SCOPE_NOT_AUTHORIZED: 4,
    ErrorCode.SCOPE_EXPIRED: 4,
    ErrorCode.TARGET_EXCLUDED: 4,
    ErrorCode.TARGET_OUT_OF_SCOPE: 4,
    ErrorCode.TASK_INVALID_TRANSITION: 4,
    ErrorCode.TASK_AUTHORIZATION_REQUIRED: 4,
    ErrorCode.TASK_AUTHORIZATION_SCOPE_MISMATCH: 4,
    ErrorCode.TASK_AUTHORIZATION_TARGET_MISMATCH: 4,
    ErrorCode.TASK_AUTHORIZATION_EXPIRED: 4,
    ErrorCode.TASK_EXECUTION_SPEC_MISMATCH: 4,
    ErrorCode.TASK_IDENTITY_IMMUTABLE: 4,
    ErrorCode.TASK_NOT_FOUND: 4,
    ErrorCode.EXECUTION_SPEC_INVALID: 4,
    ErrorCode.EXECUTION_START_FAILED: 4,
    ErrorCode.RECON_ASSET_DUPLICATE: 4,
    ErrorCode.RECON_CORRELATION_CONFLICT: 4,
    ErrorCode.RECON_PARENT_NOT_FOUND: 4,
    ErrorCode.RECON_RESULT_INVALID: 4,
    ErrorCode.RECON_AUTHORIZATION_INVALID: 4,
    ErrorCode.RECON_RECORD_INVALID: 4,
    ErrorCode.RECON_NOT_FOUND: 4,
    ErrorCode.RECON_EVIDENCE_INVALID: 4,
    ErrorCode.RECON_EVIDENCE_NOT_FOUND: 4,
    ErrorCode.RECON_EVIDENCE_ARCHIVED: 4,
    ErrorCode.RECON_EVIDENCE_PROVENANCE_INVALID: 4,
    ErrorCode.RECON_EVIDENCE_DUPLICATE: 4,
    ErrorCode.EVIDENCE_QUERY_INVALID: 4,
    ErrorCode.EVIDENCE_QUERY_UNBOUNDED: 4,
    ErrorCode.EVIDENCE_QUERY_LIMIT_EXCEEDED: 4,
    ErrorCode.EVIDENCE_QUERY_CURSOR_INVALID: 4,
    ErrorCode.EVIDENCE_QUERY_CONTEXT_INVALID: 4,
    ErrorCode.EVIDENCE_QUERY_STORAGE_FAILED: 3,
    ErrorCode.REPORT_QUERY_INVALID: 4,
    ErrorCode.REPORT_BUDGET_EXCEEDED: 4,
    ErrorCode.REPORT_DATA_INCONSISTENT: 4,
    ErrorCode.REPORT_PROJECTION_INVALID: 4,
    ErrorCode.OFFLINE_FIXTURE_INVALID: 4,
    ErrorCode.OFFLINE_FIXTURE_EXECUTION_FAILED: 4,
    ErrorCode.OFFLINE_FIXTURE_CONTEXT_INVALID: 4,
}


class CyberOSError(Exception):
    """Safe, typed application error suitable for CLI/API boundaries."""

    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        details: dict[str, Any] | None = None,
        retryable: bool = False,
        severity: ErrorSeverity = ErrorSeverity.ERROR,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}
        self.retryable = retryable
        self.severity = severity

    @property
    def exit_code(self) -> int:
        return EXIT_CODES[self.code]
