from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorSeverity(StrEnum):
    ERROR = "error"
    CRITICAL = "critical"


class ErrorCode(StrEnum):
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"
    CONFIG_INVALID = "CONFIG_INVALID"
    RUNTIME_UNSUPPORTED = "RUNTIME_UNSUPPORTED"
    PATH_NOT_WRITABLE = "PATH_NOT_WRITABLE"
    SERIALIZATION_FAILED = "SERIALIZATION_FAILED"
    INVALID_INPUT = "INVALID_INPUT"
    PLUGIN_MANIFEST_INVALID = "PLUGIN_MANIFEST_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    OPERATION_CANCELLED = "OPERATION_CANCELLED"
    DATABASE_PATH_INVALID = "DATABASE_PATH_INVALID"
    DATABASE_PARENT_NOT_WRITABLE = "DATABASE_PARENT_NOT_WRITABLE"
    DATABASE_PERMISSION_POLICY_FAILED = "DATABASE_PERMISSION_POLICY_FAILED"
    DATABASE_SYMLINK_UNSAFE = "DATABASE_SYMLINK_UNSAFE"
    DATABASE_OPEN_FAILED = "DATABASE_OPEN_FAILED"
    DATABASE_BUSY = "DATABASE_BUSY"
    DATABASE_PRAGMA_FAILED = "DATABASE_PRAGMA_FAILED"
    DATABASE_PRAGMA_MISMATCH = "DATABASE_PRAGMA_MISMATCH"
    DATABASE_CONNECTION_CLOSED = "DATABASE_CONNECTION_CLOSED"
    DATABASE_INTEGRITY_FAILED = "DATABASE_INTEGRITY_FAILED"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    MIGRATION_CHECKSUM_MISMATCH = "MIGRATION_CHECKSUM_MISMATCH"
    MIGRATION_ORDER_INVALID = "MIGRATION_ORDER_INVALID"
    MIGRATION_HISTORY_INVALID = "MIGRATION_HISTORY_INVALID"
    MIGRATION_METADATA_INVALID = "MIGRATION_METADATA_INVALID"
    TRANSACTION_NOT_ACTIVE = "TRANSACTION_NOT_ACTIVE"
    TRANSACTION_ALREADY_COMMITTED = "TRANSACTION_ALREADY_COMMITTED"
    TRANSACTION_ALREADY_ROLLED_BACK = "TRANSACTION_ALREADY_ROLLED_BACK"
    TRANSACTION_COMMIT_FAILED = "TRANSACTION_COMMIT_FAILED"
    TRANSACTION_ROLLBACK_FAILED = "TRANSACTION_ROLLBACK_FAILED"
    DOMAIN_VALIDATION_FAILED = "DOMAIN_VALIDATION_FAILED"
    WORKSPACE_ALREADY_ARCHIVED = "WORKSPACE_ALREADY_ARCHIVED"
    WORKSPACE_INVALID_STATE = "WORKSPACE_INVALID_STATE"
    ENGAGEMENT_INVALID_TRANSITION = "ENGAGEMENT_INVALID_TRANSITION"
    ENGAGEMENT_AUTHORIZATION_REQUIRED = "ENGAGEMENT_AUTHORIZATION_REQUIRED"
    ENGAGEMENT_COMPLETION_REQUIRES_END_AT = "ENGAGEMENT_COMPLETION_REQUIRES_END_AT"
    ENGAGEMENT_ALREADY_ARCHIVED = "ENGAGEMENT_ALREADY_ARCHIVED"
    PERSISTENCE_MAPPING_FAILED = "PERSISTENCE_MAPPING_FAILED"
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_NAME_CONFLICT = "WORKSPACE_NAME_CONFLICT"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    WORKSPACE_ARCHIVED = "WORKSPACE_ARCHIVED"
    ENGAGEMENT_NOT_FOUND = "ENGAGEMENT_NOT_FOUND"
    ENGAGEMENT_NAME_CONFLICT = "ENGAGEMENT_NAME_CONFLICT"
    ENGAGEMENT_WORKSPACE_IMMUTABLE = "ENGAGEMENT_WORKSPACE_IMMUTABLE"


EXIT_CODES: dict[ErrorCode, int] = {
    ErrorCode.CONFIG_NOT_FOUND: 2,
    ErrorCode.CONFIG_INVALID: 2,
    ErrorCode.RUNTIME_UNSUPPORTED: 3,
    ErrorCode.PATH_NOT_WRITABLE: 3,
    ErrorCode.SERIALIZATION_FAILED: 4,
    ErrorCode.INVALID_INPUT: 4,
    ErrorCode.PLUGIN_MANIFEST_INVALID: 5,
    ErrorCode.INTERNAL_ERROR: 10,
    ErrorCode.OPERATION_CANCELLED: 130,
    ErrorCode.DATABASE_PATH_INVALID: 3,
    ErrorCode.DATABASE_PARENT_NOT_WRITABLE: 3,
    ErrorCode.DATABASE_PERMISSION_POLICY_FAILED: 3,
    ErrorCode.DATABASE_SYMLINK_UNSAFE: 3,
    ErrorCode.DATABASE_OPEN_FAILED: 3,
    ErrorCode.DATABASE_BUSY: 3,
    ErrorCode.DATABASE_PRAGMA_FAILED: 3,
    ErrorCode.DATABASE_PRAGMA_MISMATCH: 3,
    ErrorCode.DATABASE_CONNECTION_CLOSED: 3,
    ErrorCode.DATABASE_INTEGRITY_FAILED: 3,
    ErrorCode.MIGRATION_FAILED: 3,
    ErrorCode.MIGRATION_CHECKSUM_MISMATCH: 3,
    ErrorCode.MIGRATION_ORDER_INVALID: 3,
    ErrorCode.MIGRATION_HISTORY_INVALID: 3,
    ErrorCode.MIGRATION_METADATA_INVALID: 3,
    ErrorCode.TRANSACTION_NOT_ACTIVE: 4,
    ErrorCode.TRANSACTION_ALREADY_COMMITTED: 4,
    ErrorCode.TRANSACTION_ALREADY_ROLLED_BACK: 4,
    ErrorCode.TRANSACTION_COMMIT_FAILED: 3,
    ErrorCode.TRANSACTION_ROLLBACK_FAILED: 3,
    ErrorCode.DOMAIN_VALIDATION_FAILED: 4,
    ErrorCode.WORKSPACE_ALREADY_ARCHIVED: 4,
    ErrorCode.WORKSPACE_INVALID_STATE: 4,
    ErrorCode.ENGAGEMENT_INVALID_TRANSITION: 4,
    ErrorCode.ENGAGEMENT_AUTHORIZATION_REQUIRED: 4,
    ErrorCode.ENGAGEMENT_COMPLETION_REQUIRES_END_AT: 4,
    ErrorCode.ENGAGEMENT_ALREADY_ARCHIVED: 4,
    ErrorCode.PERSISTENCE_MAPPING_FAILED: 3,
    ErrorCode.WORKSPACE_NOT_FOUND: 4,
    ErrorCode.WORKSPACE_NAME_CONFLICT: 4,
    ErrorCode.CONCURRENCY_CONFLICT: 4,
    ErrorCode.WORKSPACE_ARCHIVED: 4,
    ErrorCode.ENGAGEMENT_NOT_FOUND: 4,
    ErrorCode.ENGAGEMENT_NAME_CONFLICT: 4,
    ErrorCode.ENGAGEMENT_WORKSPACE_IMMUTABLE: 4,
}


class CyberOSError(Exception):
    """Safe, typed application error suitable for CLI/API boundaries."""

    def __init__(
        self,
        code: ErrorCode,
        message: str,
        *,
        details: dict[str, Any] | None = None,
        retryable: bool = False,
        severity: ErrorSeverity = ErrorSeverity.ERROR,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}
        self.retryable = retryable
        self.severity = severity

    @property
    def exit_code(self) -> int:
        return EXIT_CODES[self.code]
